bf16: true
bf16_full_eval: true
tf32: true
dataloader_drop_last: true
dataloader_num_workers: 6
dataloader_pin_memory: true
do_eval: true
do_train: true
evaluation_strategy: "steps"
eval_steps: 1000
gradient_accumulation_steps: 6
gradient_checkpointing: false
learning_rate: 6e-4
log_on_each_node: false
logging_steps: 1
lr_scheduler_type: "cosine_with_min_lr"
lr_scheduler_kwargs: {'min_lr_rate': 0.1}
max_grad_norm: 1.0
max_steps: 1000000
optim: "adamw_torch"
adam_beta1: 0.9
adam_beta2: 0.95
per_device_eval_batch_size: 800
per_device_train_batch_size: 800
save_steps: 1000
save_strategy: "steps"
save_total_limit: 3
torch_compile: false
warmup_ratio: 0.02
weight_decay: 0.01
save_spec_steps: 5000
push_spec_checkpoints: true
repo_id: "MolGen"
save_safetensors: false
hub_private_repo: true
include_num_input_tokens_seen: true
total_batch_size: 19200
label_smoothing_factor: 0.1