[project]
name = "novomolgpt"
version = "0.1.0"
description = "De-novo molecule generation using LLMs"
authors = ["Roshan, Kamran"]
channels = ["conda-forge", "r", "msys2", "lich", "hcc"]
platforms = ["linux-64"]

[tasks]
flash = {cmd = "export CUDA_HOME=/usr/local/cuda-12.2 MAX_JOBS=8 && git clone https://github.com/Dao-AILab/flash-attention ./flash-attention-v2 && cd ./flash-attention-v2 && python setup.py install && cd csrc/fused_dense_lib && python setup.py install && cd ../../../ && rm -rf ./flash-attention-v2"}

[dependencies]
python="3.10"
openbabel = "*"
openmm = "*"
pdbfixer = "*"
rdkit = "*"
syba = "*"
xtb="*"
xtb-python="*"
crest = "*"
lightgbm = ">=4.3.0,<4.4"
deepsmiles = ">=1.0.1,<1.1"

[pypi-dependencies]
group-selfies = { git = "https://github.com/aspuru-guzik-group/group-selfies.git"}
atomInSmiles = { git = "https://github.com/snu-lcbc/atom-in-SMILES.git"}
multiprocess = "*"
pyscf = "*"
morfeus-ml = "*"
geometric = "*"
pyberny = "*"
wurlitzer = "*"
sqlalchemy = "*"
polanyi = { git = "https://github.com/kjelljorner/polanyi.git"}
geodesic-interpolate = {git="https://github.com/virtualzx-nad/geodesic-interpolate.git"}
pyscreener = "*"
medchem = "*"
polars-u64-idx = "*"
lightning="*"
transformers = "==4.42.4"
accelerate = "==0.32.0"
datasets = "==2.20.0"
evaluate = "*"
descriptastorus = "*"
fcd-torch = { git = "https://github.com/insilicomedicine/fcd_torch.git"}
huggingface-hub = "*"
hydra-core="==1.3"
hydra-colorlog="*"
hydra-optuna-sweeper="*"
hydra-joblib-launcher="*"
torchmetrics = "*"
captum = "*"
wandb = "==0.17.4"
molvs  = "==0.1.1"
selfies = "==2.1.1"
PyTDC = "*"
pandarallel = "*"
grpcio = "*"
pyarrow = "*"
openpyxl = "*"
h5py = "*"
jupyterlab = "*"
ipywidgets = "*"
umap-learn = "*"
xgboost = "==1.0.2"
torch = "*"
torchvision = "*"
safe-mol = "*"
psutil= "==6.0.0"
py-cpuinfo= "==9.0.0"
numpy = "*"
pandas = "*"
scikit-learn = "==1.2.0"
scipy = "*"
rootutils = "*"
pre-commit = "*"
rich   = "*"
pytest  = "*"
sh = "*"
omegaconf = "*"
tqdm = "*"
pynvml = "==11.5.3"
pickleshare = "*"
sentencepiece = "==0.2.0"
trl = "*"
tabulate = "==0.9.0"
pdb-tools = "*"
packaging = "==24.1"
ninja = "*"
rd_filters = {git = "https://github.com/PatWalters/rd_filters.git"}
wheel = "*"
deepspeed = "==0.14.4"