#SMILES_BPE_157M
type: "AugmentedHC"
seed: 42
save_path: './save_augment_hc'
checkpoint: 75000
task_name: "Perindopril_MPO"
learning_rate: 5e-4
per_device_train_batch_size: 64
gradient_accumulation_steps: 1
weight_decay: 0.0
max_grad_norm: 1.0
warmup_ratio: 0.0
lr_scheduler_type: 'constant'
bf16: true
higher_is_better: true
oracle_call_budget: 10000
penalty_coef: 500
sigma: 2500
experience_replay: 32
experience_sampling: 'weighted'
early_stopping: 2000
max_length: 64
temperature: 1.0
top_k: 0
top_p: 0.0
fraction_selected: 0.1
scaffold_filter: false
wandb_tag: 'PMO_Benchmark'
only_novel_samples: false
prefill_experience_replay: true
temp_patience: 5
temp_multiplier: 1.10
temp_max: 2.0