type: "SFT"
seed: 42
task_name: "Perindopril_MPO"
save_path: './save_finetune'
checkpoint: 75000
num_epochs: 1000
per_device_train_batch_size: 512
per_device_eval_batch_size: 512
learning_rate: 1e-5
lr_scheduler_type: 'constant'
warmup_ratio: 0.
save_steps: 10
save_total_limit: 1
eval_step: 100
max_grad_norm: 1.0
bf16: true
max_length: 64
temperature: 1.0
top_k: 0
top_p: 0.0
compute_metric_eval: true
num_evaluation_samples: 500
stop_criteria_rules :
  {
    'criteria_2': {
        'task_name': 'uniqness',
        'threshold': 0.9,
        'higher': True
    },
    'criteria_3': {
        'task_name': 'novelty',
        'threshold': 0.1,
        'higher': True
    },
  }
dataset_name: "MolGen/ZINC_250K_prop"
use_random_sampling: true
top_reward_ratio: 0.1
higher_is_better: true
additional_evaluation_metrics: ["unique@1k", "IntDiv"]
wandb_tag: 'PMO_Benchmark_SFT'