model_type: "llama"
hidden_size: 512
num_hidden_layers: 12
num_attention_heads: 8
intermediate_size: 1024
use_flash_attn: true
fused_bias_fc: false
fused_mlp: false
fused_dropout_add_ln: false
residual_in_fp32: true