model_type: "llama"
hidden_size: 768
num_hidden_layers: 32
num_attention_heads: 12
intermediate_size: 3072
use_flash_attn: true
fused_bias_fc: false
fused_mlp: false
fused_dropout_add_ln: false
residual_in_fp32: true