# The Defaults List is a list in an input config that instructs Hydra how to build the output config.
defaults:
  - dataset: ZINC_1B_deep_smiles_bpe_streaming
  - model: llama-32M
  - trainer: hf_trainer_one_epoch
  - _self_

trainer:
  per_device_train_batch_size: 1600
  per_device_eval_batch_size: 1600
  gradient_accumulation_steps: 3

seed: 42
save_path: './save'
wandb_logs: true

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d-%H-%M-%S}/hydra